# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-proteomics',
                'doc_host': 'https://mtinti.github.io',
                'git_url': 'https://github.com/mtinti/nbdev-proteomics',
                'lib_path': 'nbdev_proteomics'},
  'syms': { 'nbdev_proteomics.core': { 'nbdev_proteomics.core.DatasetAnalysis': ('core.html#datasetanalysis', 'nbdev_proteomics/core.py'),
                                       'nbdev_proteomics.core.SpectronautProcessor': ( 'core.html#spectronautprocessor',
                                                                                       'nbdev_proteomics/core.py'),
                                       'nbdev_proteomics.core.SpectronautProcessor.__init__': ( 'core.html#spectronautprocessor.__init__',
                                                                                                'nbdev_proteomics/core.py'),
                                       'nbdev_proteomics.core.SpectronautProcessor.filter_protein_quantification': ( 'core.html#spectronautprocessor.filter_protein_quantification',
                                                                                                                     'nbdev_proteomics/core.py'),
                                       'nbdev_proteomics.core.SpectronautProcessor.parse_column_mapping': ( 'core.html#spectronautprocessor.parse_column_mapping',
                                                                                                            'nbdev_proteomics/core.py'),
                                       'nbdev_proteomics.core.SpectronautProcessor.process': ( 'core.html#spectronautprocessor.process',
                                                                                               'nbdev_proteomics/core.py')}}}
