# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-proteomics',
                'doc_host': 'https://mtinti.github.io',
                'git_url': 'https://github.com/mtinti/nbdev-proteomics',
                'lib_path': 'nbdev_proteomics'},
  'syms': {'nbdev_proteomics.core': {'nbdev_proteomics.core.foo': ('core.html#foo', 'nbdev_proteomics/core.py')}}}
